.\"-
.\"Copyright (c) 2021, Alexander Mishin
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd Jun 28, 2021
.Dt TM1637CTL 1
.Os
.Sh NAME
.Nm tm1637ctl
.Nd tm1637 display control program.
.Sh SYNOPSIS
.Nm
.Op Fl t Ar 0|1
.Op Fl l Ar level
.Op Fl d Ar device
.Sh OPTIONS
The
.Nm
supports the following options:
.Bl -tag -width indent
.It Fl d , Ic --device Ar device
Specify a
.Xr tm1637 4
or
.Xr tm1637d 8
character device. The compiled-in default is
.Pa /dev/tm1637 Ns ;
.It Fl l , Ic --brightness Ar level
Set the display brightness level as an integer 0..7. The display will not
turn on if it is off, but the brightness will be remembered until the next
time it is turned on; 
.It Fl t , Ic --turn Ar 0|1
Turn the display off or on. When it turns on it lights with brightness
previously remembered.
.Sh DESCRIPTION
The
.Nm
is a simple utility to set brightness level and turn on and off the display.
It can be used for manage the display by other program or script (as
.Xr cron 8
job or
.Xr bh1750-daemon 8 Ns )
.Sh SEE ALSO
.Xr tm1637 4 ,
.Xr tm1637d 8 ,
.Xr bh1750 4 ,
.Xr bh1750-daemon 8
.Sh AUTHORS
.An -nosplit
.An Alexander Mishin Aq mishin@mh.net.ru
