.\"-
.\"Copyright (c) 2021, Alexander Mishin
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd Jun 14, 2021
.Dt TM1637D 8
.Os
.Sh NAME
.Nm tm1637d
.Nd Cuse based tm1637 display userland driver.
.Sh SYNOPSIS
.Nm
.Oo Fl b Oc Oo Fl h Oc
.Fl d Ar scl Ns = Ns Ar pin Ns , Ns Ar sda Ns = Ns Ar pin Ns
.Oo , Ns Ar brightness Ns = Ns Ar level Oc Ns
.Oo , Ns Ar digits Ns = Ns Ar number Oc Ns
.Oo , Ns Ar clock
.Oc ...
.Pp
.Sh DESCRIPTION
Creates a number of character devices named
.Qo /dev/tm1637/ Ns Cm n Qc , connected to pins
.Ar scl
and
.Ar sda .
.Pp
The
.Nm
service requires the
.Xr cuse 3
kernel module to start.
.Pp
To load the driver as a module at boot time, place the following line in
.Xr loader.conf 5 :
.Bd -literal -offset indent
cuse_load="YES"
.Ed
.Pp
To configure the service, see
.Pa rc.conf.d/tm1637d.example .
.Sh OPTIONS
The
.Nm
supports the following options:
.Bl -tag -width indent
.It Fl b
Daemonize the
.Nm
after running;
.It Fl d , Ic --device
Defines th device and set its parameters:
.Bl
.It
.Ar scl Ns = Ns Ar pin , Ar sda Ns = Ns Ar pin
.Bd -ragged -offset indent -compact
Specifies the
.Ar scl
and
.Ar sda
pins of the bus to which the device is connected, where
.Ar pin
is an integer pin number;
.Ed
.It
.Ar brightness Ns = Ns Ar level
.Bd -ragged -offset indent -compact
Specifies the brightness level as an integer from 0 to 7 (Default is 2);
.Ed
.It
.Ar digits Ns = Ns Ar number
.Bd -ragged -offset indent -compact
Sets the number of digits of the display as an integer 4 or 6 (Default is 4);
.Ed
.It
.Ar clock
.Bd -ragged -offset indent -compact
Used to set a clocklike type of the display (Default is a decimal type).
.Ed
.Pp
The
.Fl d
option can be used multiple times.
.El
.It Fl h , Ic --help
Print help text showing available options;
.El
.Sh EXAMPLES
Display a string...
.Bl -compact

.It
with a colon (if You have a display with a colon):
.Dl % echo -n Qo 20:15 Qc > /dev/tm1637/0
.Dl % echo -n Qo ##:## Qc > /dev/tm1637/0

.It
without a colon:
.Dl % echo -n Qo 20 15 Qc > /dev/tm1637/0
.Dl % echo -n Qo 2015 Qc > /dev/tm1637/0
.Dl % echo -n Qo #### Qc > /dev/tm1637/0

.It
with a dots (if You have a display with a decimal dots).
Up to two dots can be used.
.Dl % echo -n Qo 3.14 Qc > /dev/tm1637/0
.Dl % echo -n Qo 01.01.21 Qc > /dev/tm1637/0

.It
right aligned number:
.Dl % echo -n Qo 15 Qc > /dev/tm1637/0
.El

Manage the display with octal commands
.Bl -compact

.It
Turn the display off:

.Dl % printf Qo \e200 Qc > /dev/tm1637/0

.It
Set a brightness level to 3:

.Dl % printf Qo \e213 Qc > /dev/tm1637/0

.It
Write a second digit '1' followed by a colon:

.Dl % printf Qo \e104\e301\e206 Qc > /dev/tm1637/0
.El

The same as above but with hexadecimal commands:

.Bl -bullet -compact
.Dl % printf $ Ns So \ex80 Sc > /dev/tm1637/0

.Dl % printf $ Ns So \ex8b Sc > /dev/tm1637/0

.Dl % printf $ Ns So \ex44\exc1\ex86 Sc > /dev/tm1637/0
.El

(See a tm1637 datasheet for commands description)

.Sh SEE ALSO
.Xr cuse 3 ,
.Xr tm1637ctl 1
.Sh AUTHORS
.An -nosplit
.An Alexander Mishin Aq mishin@mh.net.ru
