.\"-
.\"Copyright (c) 2021, Alexander Mishin
.\"All rights reserved.
.\"
.\"Redistribution and use in source and binary forms, with or without
.\"modification, are permitted provided that the following conditions are met:
.\"
.\"* Redistributions of source code must retain the above copyright notice, this
.\"  list of conditions and the following disclaimer.
.\"
.\"* Redistributions in binary form must reproduce the above copyright notice,
.\"  this list of conditions and the following disclaimer in the documentation
.\"  and/or other materials provided with the distribution.
.\"
.\"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\"DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
.\"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\"SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\"CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\"OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Dd Jun 14, 2021
.Dt TM1637D 8
.Os
.Sh NAME
.Nm tm1637d
.Nd Cuse based tm1637 display userland driver.
.Sh SYNOPSIS
.Nm
.Fl d Ar scl Ns = Ns Ar pin Ns , Ns Ar sda Ns = Ns Ar pin Ns , Ns
.Oo Ar brightness Ns = Ns Ar level
.Oc ...
.Sh OPTIONS
The
.Nm
supports the following options:
.Bl -tag -width indent
.It Fl b
Daemonize the
.Nm
after running;
.It Fl d , Ic --device Ar scl Ns = Ns Ar pin Ns , Ns Ar sda Ns = Ns Ar pin Ns , Ns Op Ar brightness Ns = Ns Ar level
Defines  the
.Ar scl
and
.Ar sda
device pins to send data to the display, where
.Ar pin
is a pin number.

Optionally a brightness
.Ar level
can be defined, an integer from 0 to 7 is acceptable
(Default is 2).

Also a
.Ar number
of digits can be set to 4 or 6 (Default is 4).

The
.Fl d
option can be used multiple times.
.It Fl h , Ic --help
Brief help.
.Sh DESCRIPTION
Creates a number of character devices like
.Qo /dev/tm1637/ Ns
.Cm n Qc , wired to
.Ar scl
and
.Ar sda
pins.
.Sh EXAMPLES
Display a string...
.Bl -bullet -compact

.It
with a colon (if You have a display with a colon):

.Dl % echo -n Qo 20:15 Qc > /dev/tm1637/0
.Dl % echo -n Qo ##:## Qc > /dev/tm1637/0

.It
without a colon:

.Dl % echo -n Qo 20 15 Qc > /dev/tm1637/0
.Dl % echo -n Qo 2015 Qc > /dev/tm1637/0
.Dl % echo -n Qo #### Qc > /dev/tm1637/0

.It
with a dots (if You have a display with a decimal dots).
Up to two dots can be used.

.Dl % echo -n Qo 3.14 Qc > /dev/tm1637/0
.Dl % echo -n Qo 01.01.21 Qc > /dev/tm1637/0

.It
right aligned number:

.Dl % echo -n Qo 15 Qc > /dev/tm1637/0
.El

Manage the display with octal commands
.Bl -bullet -compact

.It
Turn the display off:

.Dl % printf Qo \e200 Qc > /dev/tm1637/0

.It 
Set a brightness level to 3:

.Dl % printf Qo \e213 Qc > /dev/tm1637/0

.It
Write a second digit '1' followed by a colon:

.Dl % printf Qo \e104\e301\e206 Qc > /dev/tm1637/0
.El

The same as above but with hexadecimal commands:

.Bl -bullet -compact
.Dl % printf $ Ns So \ex80 Sc > /dev/tm1637/0

.Dl % printf $ Ns So \ex8b Sc > /dev/tm1637/0

.Dl % printf $ Ns So \ex44\exc1\ex86 Sc > /dev/tm1637/0
.El

(See a tm1637 datasheet for commands description)

.Sh SEE ALSO
.Xr cuse 3 ,
.Xr tm1637ctl 1
.Sh AUTHORS
.An -nosplit
.An Alexander Mishin Aq mishin@mh.net.ru
